### ISSUE TITLE
Minor bug (?) to your evaluation code

### ISSUE THREAD

**Issue by Slicerkao** [gahaalt/ICLR-SNIP-pruning#1]
Hi, 
Thanks for sharing your implementation ! I like how the weight is pruned via the method in the Prune class. However, I notice that during the training phase, your code call op() to zero out the pruned weight. But this is not done in NN.evaluation and NN.predict. I think this would cause the output accuracy to be misleading since the data is forward through a pruned network with one extra optimization step. (i.e. Weights that are supposed to be zero would no longer be zero due to the gradient update) 
Thanks for any further clarification !

**Comment by szmikler** [comment]
You're right! Pruned weights ought to be zeroed at the end of the loop, within no_grad clause, after the update. It shouldn't really change the results though. Anyway, I am planning to rewrite the whole code to find the place where my SNIP achieves worse results than in the original paper. Thank you for your finding!
